@extends('layouts.app')

@section('title', $certificate->certificate_number ?? 'Eligible Certificate')
@section('page-title', $certificate->certificate_number ?? 'Eligible Certificate')
@section('page-subtitle', $certificate->indigene->fullName().' &middot; '.$certificate->lga->name.' LGA, '.$certificate->lga->state->name.' State')

@section('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('certificates.index') }}" class="text-decoration-none"><span class="text-secondary fw-medium">Certificates</span></a></li>
    <li class="breadcrumb-item active" aria-current="page"><span class="fw-medium">{{ $certificate->certificate_number ?? 'Eligible' }}</span></li>
@endsection

@section('content')
    <div class="row g-3">
        <div class="col-xl-8">
            <div class="card bg-white border-0 rounded-3 mb-4">
                <div class="card-body p-4">
                    <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4">
                        <h5 class="mb-0 fw-semibold">Certificate</h5>
                        <div class="d-flex align-items-center gap-2">
                            @include('partials.status-badge', ['status' => $certificate->status->value])
                        </div>
                    </div>

                    <dl class="review-grid mb-4">
                        <div class="review-item"><dt>Holder</dt><dd>{{ $certificate->indigene->fullName() }}</dd></div>
                        <div class="review-item"><dt>Certificate number</dt><dd>{{ $certificate->certificate_number ?? 'Not yet allocated' }}</dd></div>
                        <div class="review-item"><dt>Issued</dt><dd>{{ optional($certificate->issued_at)->format('d/m/Y H:i') ?? '—' }}</dd></div>
                        <div class="review-item"><dt>Expires</dt><dd>{{ optional($certificate->expires_at)->format('d/m/Y') ?? 'Indefinite (policy)' }}</dd></div>
                        <div class="review-item"><dt>Signatory</dt><dd>{{ optional($certificate->lga->activeSignatory)->full_name }} &middot; {{ optional($certificate->lga->activeSignatory)->office_title }}</dd></div>
                        <div class="review-item"><dt>Origin</dt><dd>{{ $certificate->indigene->currentProfile?->ward?->name }} Ward, {{ $certificate->indigene->currentProfile?->unit?->name }}, {{ $certificate->lga->name }} LGA</dd></div>
                        <div class="review-item"><dt>Public verification URL</dt><dd><code class="small">{{ url('/v/...') }}</code> <span class="small text-secondary">(random token embedded in QR)</span></dd></div>
                        <div class="review-item"><dt>Total print occurrences</dt><dd>{{ $certificate->total_prints_cached }}</dd></div>
                    </dl>

                    @if ($certificate->currentVersion)
                        <h6 class="fw-semibold mb-3">Versions</h6>
                        <div class="table-responsive">
                            <table class="table table-sm align-middle">
                                <thead>
                                    <tr><th>Version</th><th>Generated by</th><th>Date</th><th>PDF digest (SHA-256)</th></tr>
                                </thead>
                                <tbody>
                                    @foreach ($certificate->versions as $version)
                                        <tr>
                                            <td>v{{ $version->version_no }}</td>
                                            <td>{{ optional($version->generated_by ?? null) ? $version->generatedBy?->full_name ?? '—' : '—' }}</td>
                                            <td>{{ optional($version->generated_at)->format('d/m/Y H:i') }}</td>
                                            <td><code class="small">{{ substr($version->pdf_sha256 ?? '—', 0, 16) }}&hellip;</code></td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @endif

                    <h6 class="fw-semibold mb-3 mt-4">Status history</h6>
                    <ul class="activity-timeline list-unstyled mb-0">
                        @forelse ($certificate->statusEvents as $event)
                            <li class="tl-item muted-dot">
                                <div class="fw-semibold small">
                                    {{ $event->from_status }} &rarr; {{ $event->to_status }}
                                    @if ($event->reason_code) &middot; {{ $event->reason_code }} @endif
                                </div>
                                <div class="small text-secondary">{{ optional($event->actor)->full_name }} &middot; {{ $event->created_at->format('d/m/Y H:i') }}</div>
                                @if ($event->reason_text)<div class="small mt-1">{{ $event->reason_text }}</div>@endif
                            </li>
                        @empty
                            <li class="text-secondary">No status events.</li>
                        @endforelse
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-xl-4">
            <div class="card bg-white border-0 rounded-3 mb-4">
                <div class="card-body p-4">
                    <h5 class="fw-semibold mb-3">Actions</h5>

                    @if ($certificate->status === \App\Enums\CertificateStatus::Eligible)
                        @can('issue', $certificate)
                            <form method="POST" action="{{ route('certificates.issue', $certificate) }}"
                                  data-confirm="Issue this certificate? A unique number will be allocated and an immutable version created.">
                                @csrf
                                <button class="btn btn-primary-div text-white w-100 rounded-3 fw-semibold" type="submit">
                                    <i class="ri-verified-badge-line me-1"></i> Issue certificate
                                </button>
                            </form>
                        @endcan
                    @endif

                    @if ($canPrint)
                        <form method="POST" action="{{ route('certificates.print-events', $certificate) }}"
                              target="_blank" id="print-form"
                              data-confirm="Generate a printable copy? This is counted as a print occurrence.">
                            @csrf
                            <input type="hidden" name="idempotency_key" value="{{ str()->uuid() }}">
                            <button class="btn btn-brand-green w-100 rounded-3 fw-semibold" type="submit">
                                <i class="ri-printer-line me-1"></i>
                                Print certificate
                            </button>
                        </form>
                        <p class="small text-secondary mt-2 mb-0">
                            Opens the approved certificate in your browser. Every copy is counted and recorded.
                        </p>
                    @endif

                    @if ($canManageStatus && $certificate->status !== \App\Enums\CertificateStatus::Eligible && $certificate->status !== \App\Enums\CertificateStatus::Revoked && $certificate->status !== \App\Enums\CertificateStatus::Superseded)
                        <hr>
                        <h6 class="fw-semibold mb-2 text-secondary">Status actions</h6>

                        @if ($certificate->status === \App\Enums\CertificateStatus::Active)
                            <form method="POST" action="{{ route('certificates.suspend', $certificate) }}" class="mb-2"
                                  data-confirm="Suspend this certificate? Public verification will show SUSPENDED.">
                                @csrf
                                <div class="d-flex gap-2">
                                    <select class="form-select form-select-sm" name="reason_code" required>
                                        <option value="">Reason&hellip;</option>
                                        <option value="investigation">Under investigation</option>
                                        <option value="policy_review">Policy review</option>
                                        <option value="other">Other</option>
                                    </select>
                                    <button class="btn btn-outline-warning rounded-3 fw-semibold flex-shrink-0" type="submit">Suspend</button>
                                </div>
                                <input class="form-control form-control-sm mt-2" name="reason_text" type="text" placeholder="Details (required)" maxlength="2000" required>
                            </form>
                        @endif

                        @if ($certificate->status === \App\Enums\CertificateStatus::Suspended)
                            <form method="POST" action="{{ route('certificates.reinstate', $certificate) }}" class="mb-2"
                                  data-confirm="Reinstate this certificate?">
                                @csrf
                                <input type="hidden" name="reason_code" value="investigation_closed">
                                <input class="form-control form-control-sm mb-2" name="reason_text" type="text" placeholder="Details (required)" maxlength="2000" required>
                                <button class="btn btn-outline-success w-100 rounded-3 fw-semibold" type="submit">Reinstate</button>
                            </form>
                        @endif

                        @if (in_array($certificate->status->value, ['active', 'suspended'], true))
                            <form method="POST" action="{{ route('certificates.reissue', $certificate) }}" class="mb-2"
                                  data-confirm="Start a reissue? The current version will be superseded and a new certificate number allocated.">
                                @csrf
                                <div class="mb-2">
                                    <select class="form-select form-select-sm" name="reason_code" required>
                                        <option value="">Reissue reason&hellip;</option>
                                        <option value="material_change">Material change approved</option>
                                        <option value="compromise">Possible compromise</option>
                                        <option value="other">Other</option>
                                    </select>
                                </div>
                                <input class="form-control form-control-sm mb-2" name="reason_text" type="text" placeholder="Details (required)" maxlength="2000" required>
                                <button class="btn btn-outline-secondary w-100 rounded-3 fw-semibold" type="submit">Reissue (supersede)</button>
                            </form>

                            <form method="POST" action="{{ route('certificates.revoke', $certificate) }}"
                                  data-confirm="REVOKE this certificate? Revocation is final and recorded; public verification will show REVOKED.">
                                @csrf
                                <div class="mb-2">
                                    <select class="form-select form-select-sm" name="reason_code" required>
                                        <option value="">Revocation reason&hellip;</option>
                                        <option value="fraud">Fraudulent acquisition</option>
                                        <option value="court_order">Court order</option>
                                        <option value="wrongful_issue">Wrongful issue</option>
                                        <option value="other">Other</option>
                                    </select>
                                </div>
                                <input class="form-control form-control-sm mb-2" name="reason_text" type="text" placeholder="Details (required)" maxlength="2000" required>
                                <button class="btn btn-destructive w-100 rounded-3 fw-semibold" type="submit">
                                    <i class="ri-forbid-2-line me-1"></i> Revoke certificate
                                </button>
                            </form>
                        @endif
                    @endif
                </div>
            </div>

            <div class="card bg-white border-0 rounded-3 mb-4">
                <div class="card-body p-4">
                    <h5 class="fw-semibold mb-3">Public verification</h5>
                    <p class="small text-secondary">
                        The QR code on the certificate opens a random, unguessable verification URL.
                        It never contains the NIN or private applicant data.
                    </p>
                    <a href="{{ route('certificates.verify.token', ['token' => '--token-is-random--']) }}" class="btn btn-outline-secondary w-100 rounded-3 fw-semibold" onclick="return false;" title="Tokens are random and hashed; scan the certificate QR instead">
                        <i class="ri-qr-scan-line me-1"></i> Scan the certificate QR to verify
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection
